version: '3.3'
services:
  db:
    container_name: parking_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'parking_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: